### ISSUE TITLE
No epoch info for SNLS spectra?

### ISSUE THREAD

**Issue by guillochon** [astrotransients/sne-external-spectra#4]
It seems that the individual spectra files give no hint as to when they were collected. Would be nice to have this information in the future.

**Comment by jparrent** [comment]
@guillochon I believe this is because epochs for this sample were estimated with SALT2 fits to light curves. The estimated epochs are in the appendix tables of C. Balland et al. 2009
http://www.aanda.org/articles/aa/pdf/2009/43/aa12246-09.pdf

I can start adding these to the .json files once the spectra are synced. Otherwise point me elsewhere.

**Comment by guillochon** [comment]
There's a VizieR table with the date info for each spectrum, I'm now importing from this table in the import script to associate dates to each SNLS spectra. Closing.
